export const PROFILES = {
  minimal: {
    mode: 'read',
    methods: [
      'users.get',
      'users.search',
      'friends.get',
      'wall.get',
      'groups.get',
      'photos.get',
    ],
  },
  social: {
    mode: 'read',
    sections: ['users', 'friends'],
    methods: [
      'wall.get',
      'groups.get',
      'photos.get',
    ],
  },
  content_read: {
    mode: 'read',
    methods: [
      'wall.get',
      'wall.search',
      'wall.getComments',
      'wall.getReposts',
      'photos.get',
      'photos.getAlbums',
      'photos.getById',
      'photos.getAll',
      'photos.getUserPhotos',
      'video.get',
      'video.search',
      'video.getAlbums',
      'video.getComments',
      'docs.get',
      'docs.getById',
      'docs.search',
      'notes.get',
      'notes.getById',
      'notes.getComments',
      'board.getTopics',
      'board.getComments',
      'stories.get',
      'stories.getById',
      'stories.getReplies',
      'polls.getById',
      'polls.getVoters',
      'pages.get',
      'pages.getHistory',
    ],
  },
  content_publish: {
    mode: 'all',
    methods: [
      'wall.post',
      'wall.edit',
      'wall.delete',
      'wall.createComment',
      'wall.deleteComment',
      'wall.restore',
      'wall.pin',
      'wall.unpin',
      'wall.repost',
      'wall.editComment',
      'photos.save',
      'photos.edit',
      'photos.delete',
      'photos.createComment',
      'photos.deleteComment',
      'photos.restoreComment',
      'video.save',
      'video.edit',
      'video.delete',
      'video.createComment',
      'video.deleteComment',
      'notes.add',
      'notes.edit',
      'notes.delete',
    ],
  },
  community_manager: {
    mode: 'all',
    sections: ['wall', 'board', 'groups'],
    methods: [
      'photos.get',
      'photos.getUploadServer',
      'photos.save',
      'photos.edit',
      'photos.delete',
      'video.get',
      'video.save',
      'video.edit',
      'video.delete',
      'users.get',
      'users.search',
      'utils.checkLink',
      'utils.resolveScreenName',
      'utils.getServerTime',
    ],
    excludeMethods: ['groups.leave', 'groups.join'],
  },
  messenger: {
    mode: 'all',
    sections: ['messages'],
    methods: [
      'users.get',
      'photos.getMessagesUploadServer',
    ],
    excludeMethods: [
      'messages.deleteConversation',
      'messages.deleteChatPhoto',
      'messages.removeChatUser',
    ],
  },
  analytics: {
    mode: 'read',
    sections: ['stats'],
    methods: [
      'wall.get',
      'wall.search',
      'wall.getComments',
      'wall.getReposts',
      'groups.get',
      'groups.getById',
      'groups.getMembers',
      'groups.search',
      'users.get',
      'users.search',
      'users.getFollowers',
      'users.getSubscriptions',
      'likes.getList',
      'likes.isLiked',
    ],
  },
  money: {
    mode: 'money',
  },
  ads: {
    mode: 'money',
    sections: ['ads'],
    methods: [
      'users.get',
      'groups.get',
      'utils.checkLink',
      'utils.getServerTime',
      'utils.resolveScreenName',
    ],
  },
  market: {
    mode: 'money',
    sections: ['market'],
    methods: [
      'photos.get',
      'photos.getUploadServer',
      'photos.save',
      'groups.get',
      'groups.getById',
      'users.get',
    ],
  },
  commerce: {
    mode: 'money',
    sections: ['market', 'orders', 'store', 'gifts', 'donut'],
    methods: [
      'users.get',
      'groups.get',
      'groups.getById',
      'photos.get',
      'photos.getUploadServer',
      'photos.save',
    ],
  },
  search: {
    mode: 'read',
    methods: [
      'users.search',
      'groups.search',
      'wall.search',
      'photos.search',
      'video.search',
      'docs.search',
      'market.search',
      'newsfeed.search',
      'friends.search',
    ],
  },
  full_read: {
    mode: 'read',
    excludeSections: ['ads', 'secure'],
  },
  full: {
    mode: 'all',
  },
};

export function getProfileNames() {
  return Object.keys(PROFILES);
}
